spring.application.name=api-cursos

# URL de conexao com o banco (crie o banco 'api_cursos' no pgAdmin/DBeaver)
spring.datasource.url=jdbc:postgresql://localhost:5432/api_cursos
spring.datasource.username=postgres
spring.datasource.password=admin

# Configurações do JPA/Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Atualiza a estrutura do banco automaticamente util em dev)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true